### ISSUE TITLE
The Diamond Cruise data redundacy

### ISSUE THREAD

**Issue by jnasoy** [BlankerL/DXY-2019-nCoV-Crawler#65]
It seems like there are multiple data entries for The Diamond Cruise

![Screenshot_2020-02-18 https lab isaaclin cn](https://user-images.githubusercontent.com/7227288/74784477-42632a80-52a8-11ea-86e6-6f9a2c1a03e3.png)

By the way, great job on the API, been using it in my own visualization. What do you think about adding coordinates? I can help with the map data for the coordinates based on your api.

**Comment by BlankerL** [comment]
Thank you for reporting this. I suppose Ding Xiang Yuan does not fix the name and punctuation marks in Chinese, so there are redundant data. 

I suppose you could just use APIs offered by Google Maps or some open-source maps to meet your needs. This project only crawls and saves data for visualization and scientific research, I can offer English names of the cities or the zip codes because foreign people need them to distinguish city names. But this project is not supposed to wrap up everything and might not be a one-stop service for all the development requirements. 

By the way, you can just use [ECharts](https://www.echartsjs.com/en/index.html) to visualize all the data simply with the city name, rather than using the coordinates.

**Comment by BlankerL** [comment]
I went through the database and found Ding Xiang Yuan has already fixed the name for Diamond Princess, so I fixed the problem in historical data. 

I also add the English name "Diamond Princess Cruise Ship", which is provided by its [official website](https://www.princess.com/ships-and-experience/ships/di-diamond-princess/), in the latest commit [`3219f3e`](https://github.com/BlankerL/DXY-COVID-19-Crawler/commit/3219f3e6b59617f6a959183a06dbed31accc6e12).
