### ISSUE TITLE
Timezone in the updateTime fields

### ISSUE THREAD

**Issue by itachiluan** [BlankerL/DXY-2019-nCoV-Crawler#77]
Hi, firstly again thanks so much for the effort in maintaining this project.
From the code I can see that the `crawl_timestamp` is generated by way of `datetime.datetime.now()`, which would use the local time whichever the running machine is at (which I assume would be Beijing time (CST) ?).
My question would be that, what timezone is the time updateTime fields in?

And some suggestion would be, to either:
1. incorporate `tzinfo` in the code, i.e.:
`import pytz`
`timeZone = pytz.timezone("Asia/Shanghai")`
`self.crawl_timestamp = int(datetime.datetime.timestamp(datetime.datetime.now(timeZone)) * 1000)`
of sorts.

2. incorporate utc time altogether, `datetime.datetime.utcnow()`, but that would introduce a significant change in the timestamp in all data (provided that the timestamps were in Beijing time of course).

I guess the first thing to do is probably to state the timezone this project is using in the README file? Since there are significant amount of requests coming from outside of China, timezone confusion would be an issue. Thanks!

抱歉用英语了。。。只是希望知道这个项目的老外朋友们也能看到= =！

**Comment by BlankerL** [comment]
Hello, 

As you can see [here](https://github.com/BlankerL/DXY-COVID-19-Crawler/blob/adc07bb5759a9d983bd0ff92938f02954655f91b/service/crawler.py#L95), the `updateTime` is `crawl_timestamp`, and it is not CST but UTC. 

#### Explanation about `updateTime`

I initiate the `cralw_timestamp` in the [`crawler()` function](https://github.com/BlankerL/DXY-COVID-19-Crawler/blob/adc07bb5759a9d983bd0ff92938f02954655f91b/service/crawler.py#L42) rather than initiate in each parser function because I would like to make this timestamp consistent across the collections. For example, the crawler initiated at `1584267165`, and as you can see, in DXYArea, DXYOverall and other collections, all the data updated within this minute will be labeled as `1584267165`, but if I generated the timestamp in each parser, the timestamp will be different and people need extra efforts to make sure whether these data were crawled at the same time or not. 

#### Explanation about `timezone`

As mentioned in the [documentation of `datetime.datetime.now()`](https://docs.python.org/2/library/datetime.html#datetime.datetime.now), this function will return the current time of the platform's local date and time. With the `datetime.datetime.timestamp()` function, the time will be converted to UTC timestamp by loading your current timezone and convert the datetime into UTC time automatically. 

Maybe you can have a test on your computer, 
On [Unix TimeStamp Converter](https://www.unixtimestamp.com/index.php), we can see the current timestamp is `1584268793`.
![Current UTC](https://user-images.githubusercontent.com/24969376/76699995-d7154880-66ed-11ea-9d48-e90a71fd6389.png)

```python
datetime.datetime.timestamp(datetime.datetime.now())
>>> 1584268696.323536
# Close to UTC
```
```python
datetime.datetime.timestamp(datetime.datetime.utcnow())
>>> 1584239941.910548
# Does not match the UTC
```

The [documentation for `datetime.datetime.utcnow()`] is a little bit ambiguous, but as far as I can tell, this function will directly return the current UTC in datetime format, but the `datetime.datetime.timestamp()` will get the local timezone and calculate the "UTC" with -8:00 and consequently the result is wrong. 

#### Conclusion
Therefore, the `updateTime` in the database is UTC timestamp, and I think it is a consensus in Computer Science world (but I am also not sure) because people could load the UTC timestamp and convert to their local time with ease. 

But thank you for mentioning this. By reading the documentation, I found this function `datetime.datetime.timestamp(datetime.datetime.now())` could actually be replaced by `datetime.datetime.now().timestamp()` and even by `time.time()` directly, both of which are much more efficient and decent than `datetime.datetime.timestamp(datetime.datetime.now())`.

**Comment by itachiluan** [comment]
Hi Lin,
Cool, that's really good to know!

Ye I was looking at the historical data I got from the API couple of days ago, however the updateTime was only a timestamp so I couldn't be sure which timezone they were in.
To be honest I'm not sure about the conventions but you are absolutely right, it is definitely a good idea to incorporate UTC in the raw data. (when I was crawling the data from Tencent, their timestamps were all in string format with no tzinfo at all, I have to scrap in realtime to realize that they were using CST.. eewh..).
So since I had this bad experience with Tencent, naturally I had to be sure which time zone the timestamps were in, in the historical data. Thanks very much for clarifying that :).
btw, I'm not sure if `datetime.datetime.timestamp()` does that extra thing, the behaviour on my server (which is in UTC time) was quite normal.......

    >>> datetime.datetime.timestamp(datetime.datetime.now())
    1584271839.670521
    >>> datetime.datetime.timestamp(datetime.datetime.utcnow())
    1584271850.540333

Maybe there's some issue with some particular version? I'll maybe sometime later look into that...
And ye, those two methods in the end are much more concise :)

**Comment by BlankerL** [comment]
Maybe I need to make it more clear. 

`datetime.datetime.now()` returns the platform's/system's local date and time. For example, we are in GMT+8 area, so
```python
datetime.datetime.now()
>>> datetime.datetime(2020, 3, 15, 19, 41, 27, 704557)
```
`datetime.datetime.utcnow()` returns the UTC date and time, you can suppose this is the time of Greenwich (GMT+0). 
```python
datetime.datetime.utcnow()
>>> datetime.datetime(2020, 3, 15, 11, 41, 47, 523299)
```

However, the `datetime.datetime.timestamp()` will not know which timezone the input datetime belongs to, so it will take into granted that the timezone of input datetime is the same as the timezone of your platform/system. 

Therefore, when we are in GMT+8 area, 
```python
# Here, the datetime.now() is the system's time, which is GMT+8 time. 
# datetime.timestamp() will convert it to GMT+0 by cutting off 8 hours. 
datetime.datetime.timestamp(datetime.datetime.now())
>>> 1584272762.984888
```
```python
# Here, the datetime.now() is already UTC time, which is GMT+0 time. 
# But, the datetime.timestamp() does not know, so it will cut off 8 hours because the system is in GMT+8 area. 
datetime.datetime.timestamp(datetime.datetime.utcnow())
>>> 1584243951.19349
```

For your server, it is in GMT+0 area, so the `datetime.datetime.timestamp(`) will actually cut off 0 hours, and the `datetime.datetime.now()` and `datetime.datetime.utcnow()` is the same.

**Comment by itachiluan** [comment]
Hi Lin,

Thanks very much for the reply, after testing it on my local machine, I know what you mean now :)
Apologies for taking up your time, but I'm happy that I learned something new :) 👍 

This is a really strange behaviour by `datetime.datetime.timestamp()` to be honest - -!  A function should only do one thing, instead of doing one thing this one implicitly convert the timezone by whatever it thinks the data was fed into and converted it. I thought writing `utcnow()` in the code would be more explicit but turns out it might create some really nasty bugs when used with `timestamp()`....
Again thanks so much for bringing it up, now I'll have that keep in mind :)


Edit: well.. seems that `datetime.datetime.fromtimestamp()` will also do that same thing... so when I tried to convert 1584276263 into datetime on my local machine and server, it returned CST time and UTC time respectively..... alright maybe it will not create the bug I thought.. as long as I was using python? .... maybe I'll try some timestamp with different languages....

Edit2: Well... I guess I'll just have to remember this ambiguous behaviour of `datetime.timestamp()` and `datetime.fromtimestamp()`... I tried the same timestamp in Node and obviously on my local machine, Node and Python returned different datetime(Node returned the UTC time and Python returned CST time). So I'll just have to remember this behaviour of python. Hadn't I looked into this I'd probably thought OK time in the data is in UTC so I'd shift +8:00 to get local time however in fact it was already converted by `datetime.fromtimestamp()`.....

**Comment by BlankerL** [comment]
I suppose the `datetime.timestamp()` and `datetime.fromtimestamp()` will just take the timezone of your machine into consideration automatically. 

As you can see [here](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp), for the `datetime.fromtimestamp(timestamp, tz=None)`, "if optional argument `tz` is None or not specified, the timestamp is converted to the platform’s local date and time, and the returned datetime object is naive." It seems that the `datetime.timestamp()` and `datetime.fromtimestamp()` will simply convert the UTC time to your machine's local time. 

Therefore, if you would like to make sure the codes work perfectly on servers in the different timezones, you might need to manually specify the `tz` parameter in your codes and distribute the codes to different servers. Alternatively, you might change your machine's time into the same timezone.

**Comment by itachiluan** [comment]
Hi Lin,

Yes, I suppose I should do according to the advice you mentioned above :) again, thanks!
